export enum RequestTypeCode {
  LEAVE_REQUEST = 'LEAVE_REQUEST',
  ATTENDANCE_UPDATE = 'ATTENDANCE_UPDATE',
  EQUIPMENT_BORROW = 'EQUIPMENT_BORROW',
  OVERTIME_REQUEST = 'OVERTIME_REQUEST',
  WORK_SHIFT_CHANGE = 'WORK_SHIFT_CHANGE',
}
