import { LeaveTypeCode } from '../../modules/leave-request/enums/leave-type-code.enum';
import { RequestTypeCode } from '../../modules/request/enums/request-type-code.enum';

export const permissionCodes = [
  'approval-flow:create',
  'approval-flow:delete',
  'approval-flow:read',
  'approval-flow:update',
  'approval-flow-step:create',
  'approval-flow-step:delete',
  'approval-flow-step:read',
  'approval-flow-step:update',
  'approval-step-template:create',
  'approval-step-template:delete',
  'approval-step-template:read',
  'approval-step-template:update',
  'attendance:read',
  'attendance:read-all',
  'attendance:read-dashboard',
  'attendance:update',
  'department:create',
  'department:delete',
  'department:read',
  'department:update',
  'employee:create',
  'employee:delete',
  'employee:read',
  'employee:read-all',
  'employee:update',
  'employee:update-status',
  'leave-balance:adjust',
  'leave-balance:grant',
  'leave-balance:read',
  'leave-type:create',
  'leave-type:delete',
  'leave-type:read',
  'leave-type:update',
  'permission:read',
  'permission:update',
  'position:create',
  'position:delete',
  'position:read',
  'position:update',
  'request:approve',
  'request:cancel',
  'request:create',
  'request:read',
  'request:read-all',
  'request:reject',
  'request-type:create',
  'request-type:delete',
  'request-type:read',
  'request-type:update',
  'role:create',
  'role:delete',
  'role:permission',
  'role:read',
  'role:update',
  'user:assign-role',
  'user:create',
  'user:read',
  'user:reset-password',
  'user:update',
  'user:update-status',
  'work-shift:create',
  'work-shift:delete',
  'work-shift:read',
  'work-shift:update',
] as const;

export const requestTypes = [
  {
    code: RequestTypeCode.LEAVE_REQUEST,
    name: 'Leave request',
    description: 'Employee leave request',
    handlerKey: RequestTypeCode.LEAVE_REQUEST,
  },
  {
    code: RequestTypeCode.ATTENDANCE_UPDATE,
    name: 'Attendance adjustment',
    description: 'Attendance correction request',
  },
  {
    code: RequestTypeCode.EQUIPMENT_BORROW,
    name: 'Equipment borrowing',
    description: 'Equipment borrowing request',
  },
  {
    code: RequestTypeCode.OVERTIME_REQUEST,
    name: 'Overtime request',
    description: 'Employee overtime request',
  },
  {
    code: RequestTypeCode.WORK_SHIFT_CHANGE,
    name: 'Work shift change',
    description: 'Employee work shift change request',
  },
] as const;

export const leaveTypes = [
  {
    code: LeaveTypeCode.ANNUAL_LEAVE,
    name: 'Annual leave',
    description: 'Paid annual leave deducted from the employee balance',
    isPaid: true,
    annualQuota: 12,
    deductFromBalance: true,
  },
  {
    code: LeaveTypeCode.UNPAID_LEAVE,
    name: 'Unpaid leave',
    description: 'Unpaid leave that does not use the annual leave balance',
    isPaid: false,
    annualQuota: 0,
    deductFromBalance: false,
  },
] as const;

export const defaultWorkShift = {
  name: 'Standard office shift',
  startTime: '08:00:00',
  endTime: '17:00:00',
  breakStart: '12:00:00',
  breakEnd: '13:00:00',
  lateAfter: '08:00:00',
  standardMinutes: 480,
  isActive: true,
  isDefault: true,
} as const;
